---
- name: Retrieve instance metadata
  shell: curl -sS http://169.254.169.254/latest/dynamic/instance-identity/document
  register: curl_metadata_result
  changed_when: False  # Don't mark read-only tasks as changed.

- name: Debug curl_metadata_result
  debug:
      var: curl_metadata_result

- name: Set some facts from metadata
  set_fact:
      aws_region: "{{ curl_metadata_result.stdout | from_json | json_query('region') }}"
      aws_account_id: "{{ curl_metadata_result.stdout | from_json | json_query('accountId') }}"
      aws_instance_id: "{{ curl_metadata_result.stdout | from_json | json_query('instanceId') }}"

- name: debug aws_instance_id
  debug:
      var: aws_instance_id

- name: Sanity checks
  assert:
    that:
      - (aws_instance_id | length) == 19
      - aws_instance_id.startswith("i-")

- name: Gather the complete instance info (with tags)
  ec2_instance_info:
    region: "{{ aws_region }}"
    instance_ids:
      - "{{ aws_instance_id }}"
  register: ec2_facts
