---
- name: Identify the default network interface
  set_fact:
    default_nic: "{{ ansible_default_ipv4.interface }}"

- name: Filter out the default network interface, and the local interface (lo)
  set_fact:
    secondary_interface_names: "{{ ansible_interfaces | difference([default_nic, 'lo']) }}"

- name: Debug secondary_interface_names
  debug:
      var: secondary_interface_names

- name: Loop over secondary_interface_names and configure the ethernet devices they correspond to
  include_tasks: ./configure_ena_device.yml
  loop: "{{ secondary_interface_names }}"
  loop_control:
    loop_var: eth_interface_name
